CONFIDENCE_WEIGHTS = {
    "classification": 0.30,
    "grouping": 0.35,
    "model": 0.20,
    "color": 0.10,
    "title": 0.05,
}

MAX_IMAGES_PER_ITEM = 12

IGNORED_IMAGE_TERMS = [
    "logo",
    "avatar",
    "icon",
    "sprite",
    "favicon",
    "placeholder",
    "loading",
    "banner",
    "navigation",
    "header",
    "footer",
]

NAME_NOISE_TERMS = [
    "album",
    "folder",
    "page",
    "product",
    "item",
    "new arrival",
    "photo",
    "image",
    "img",
    "copy",
]

CATEGORY_RULES = {
    "Tenis": [
        "air force",
        "air max",
        "new balance",
        "sneaker",
        "sneakers",
        "shoe",
        "shoes",
        "trainer",
        "trainers",
        "jordan",
        "dunk",
        "shox",
        "vomero",
        "campus",
        "yeezy",
        "samba",
        "gazelle",
    ],
    "Camisetas": ["oversized tee", "boxy tee", "t-shirt", "tshirt", "camiseta", "tee"],
    "Camisas": ["button shirt", "dress shirt", "camisa social", "camisa", "shirt"],
    "Moletons": ["zip hoodie", "pullover hoodie", "sweatshirt", "crewneck", "pullover", "sweater", "moletom", "hoodie"],
    "Jaquetas": ["windbreaker", "varsity", "jacket", "coat", "puffer", "jaqueta", "casaco"],
    "Calcas": ["cargo pants", "denim pants", "sweatpants", "track pants", "trousers", "pants", "jeans", "calca"],
    "Shorts": ["shorts", "bermuda", "short"],
    "Conjuntos": ["matching set", "two piece", "2 piece", "tracksuit", "conjunto", "set"],
    "Bones": ["snapback", "beanie", "bone", "touca", "cap", "hat"],
    "Bolsas": ["shoulder bag", "crossbody", "backpack", "mochila", "bolsa", "tote", "bag"],
    "Acessorios": [
        "jewelry",
        "jewellery",
        "jewel",
        "sunglasses",
        "keychain",
        "necklace",
        "bracelet",
        "earring",
        "pendant",
        "chain",
        "glasses",
        "wallet",
        "carteira",
        "pulseira",
        "oculos",
        "meias",
        "scarf",
        "socks",
        "belt",
        "ring",
        "cinto",
        "colar",
        "anel",
    ],
}

KNOWN_MODELS = {
    "nike": ["air max 95", "air max dn", "air force", "dunk", "shox", "vomero 5", "vomero premium"],
    "jordan": ["jordan 1 low", "jordan 1 high", "jordan 3", "jordan 4", "jordan 6", "jordan 11"],
    "adidas": ["campus 00s", "campus 00", "samba", "gazelle", "yeezy 350 v2", "yeezy 700", "yeezy slide"],
    "new balance": ["9060", "530", "550", "1000", "1906a", "740"],
    "essentials": ["zip hoodie", "pullover hoodie", "crewneck", "sweatpants", "t-shirt"],
    "chrome hearts": ["zip hoodie", "t-shirt", "tee", "crewneck"],
}

COLOR_RULES = {
    "Triple Black": ["triple black"],
    "Black White": ["black white", "preto branco"],
    "University Blue": ["university blue"],
    "Royal Blue": ["royal blue"],
    "Light Grey": ["light grey", "light gray", "cinza claro"],
    "Navy": ["navy", "azul marinho"],
    "Multi Color": ["multi color", "multicolor", "colorido"],
    "Light Oatmeal": ["light oatmeal"],
    "Oatmeal": ["oatmeal"],
    "Black": ["black", "preto"],
    "White": ["white", "branco"],
    "Grey": ["grey", "gray", "cinza"],
    "Blue": ["blue", "azul"],
    "Red": ["red", "vermelho"],
    "Burgundy": ["burgundy", "vinho"],
    "Brown": ["brown", "marrom"],
    "Beige": ["beige", "bege"],
    "Cream": ["cream", "creme"],
    "Sail": ["sail"],
    "Green": ["green", "verde"],
    "Olive": ["olive", "oliva"],
    "Pink": ["pink", "rosa"],
    "Purple": ["purple", "roxo"],
    "Orange": ["orange", "laranja"],
    "Yellow": ["yellow", "amarelo"],
}
